apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario
  template:
    metadata:
      labels:
        app: inventario
    spec:
      containers:
        - name: inventario
          image: inventario-local:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
