apiVersion: v1
kind: Service
metadata:
  name: inventario-service
spec:
  selector:
    app: inventario
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
